project:
  type: book
  output-dir: docs

website:
  site-url: https://github.com/Fpadt/gh_pages_test

date:        last-modified
date-format: long

authors:
  - name:    Floris Padt
    orcid:   0009-0006-4729-1783
    corresponding: true
    email: floris@smart-r.nl
    url: https://www.linkedin.com/in/florispadt    
    roles:
      - Conceptualization
      - Data curation
      - Formal analysis
      - Investigation
      - Methodology
      - Software
      - Validation
      - Visualization
      - Writing     
    degrees: 
      - MSc.
    affiliations: 
      - name:         EAISI - Technical University Eindhoven
        city:         Eindhoven
        country:      The Netherlands
        department:   EAISI Academy
        group:        Professional education
        url:          https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai
  - name:   Ieke Le Blanc
    url: https://www.tue.nl/en/education/professional-education/current-programs/eaisi-academy/lecturers/dr-ieke-le-blanc
    roles:
      - Supervisor
      - Mentor     
    degrees: 
      - Dr.
    affiliations: 
      - name:         EAISI - Technical University Eindhoven
        city:         Eindhoven
        country:      The Netherlands
        department:   EAISI Academy
        group:        Professional education
        url:          https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai 

crossref:
  def-prefix: def
  def-title:  def
    
execute:
  freeze:  false
  echo:    false
  output:  true
  include: false
  warning: false

editor: source

book:
  title: "My Minimal Quarto Book"
  repo-url: https://github.com/Fpadt/gh_pages_test
  repo-actions: [source, issue]
  downloads: [pdf] 
  sharing: [twitter, facebook, linkedin]
  page-navigation: true # Explicit navigation controls
  page-footer:
    left: "© 2025 Floris Padt: Pythia's Advice"
    # center: ""
    right: "[EAISI](https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai)"
  
  chapters:
    - part: "Foundations"
      chapters:
        - index.qmd
        # - notebooks/intro-crisp-dm.qmd
    - part: "Project Phases"
      chapters:
        # - nb/01_business_understanding_rev.qmd
        - nb/02_data_understanding_rev.qmd
        - nb/03_data_preparation_rev.qmd
        - nb/04_modelling_rev.qmd
        - nb/05_evaluation_rev.qmd
        - nb/06_deployment_rev.qmd
        
  # chapters:
  #   - index.qmd
  #   - chapter1.qmd
  #   - chapter2.qmd
  #   - references.qmd

format:
  html:
    # base-href: "/EAISI-Paper/"
    # include-in-header:
    #   text: |
    #     <base href="/EAISI-Paper/">
    # include-before-body:
    #   text: |
    #     <script>
    #       // Ensure base tag exists
    #       if (!document.querySelector('base')) {
    #         var base = document.createElement('base');
    #         base.href = '/EAISI-Paper/';
    #         document.head.prepend(base);
    #       }
    #     </script>
    # Banner configuration
    title-block-banner: true
    title-block-style: default
    # Custom banner color
    title-block-banner-color: "#FFFFFF"
    background-color: "#004D40"
    toc:                true
    code-fold:          true  
    lightbox:           true
    comments:
      hypothesis:       false
    number-sections:    true
    colorlinks:         true
    highlight-style:    github
    theme:
      light:            [flatly]
      dark:             [darkly]
    respect-user-color-scheme: false    
    fontsize:           "10"
    crossrefs-hover:    true 