project:
  type: book
  output-dir: docs

website:
  site-url: https://github.com/Fpadt/gh_pages_test

date:        last-modified
date-format: long

authors:
  - name:    Floris Padt
    orcid:   0009-0006-4729-1783
    corresponding: true
    email: floris@smart-r.nl
    url: https://www.linkedin.com/in/florispadt    
    roles:
      - Conceptualization
      - Data curation
      - Formal analysis
      - Investigation
      - Methodology
      - Software
      - Validation
      - Visualization
      - Writing     
    degrees: 
      - MSc.
    affiliations: 
      - name:         EAISI - Technical University Eindhoven
        city:         Eindhoven
        country:      The Netherlands
        department:   EAISI Academy
        group:        Professional education
        url:          https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai
  - name:   Ieke Le Blanc
    url: https://www.tue.nl/en/education/professional-education/current-programs/eaisi-academy/lecturers/dr-ieke-le-blanc
    roles:
      - Supervisor
      - Mentor     
    degrees: 
      - Dr.
    affiliations: 
      - name:         EAISI - Technical University Eindhoven
        city:         Eindhoven
        country:      The Netherlands
        department:   EAISI Academy
        group:        Professional education
        url:          https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai 

crossref:
  def-prefix: def
  def-title:  def
    
execute:
  freeze:  false
  echo:    false
  output:  true
  include: false
  warning: false

editor: source

book:
  title: "My Minimal Quarto Book"
  repo-url: https://github.com/Fpadt/gh_pages_test
  repo-actions: [source, issue]
  downloads: [pdf] 
  sharing: [twitter, facebook, linkedin]
  page-navigation: true # Explicit navigation controls
  page-footer:
    left: "Powered by [Quarto](https://quarto.org/)"
    center: "© 2025 Floris Padt"
    right: "[EAISI - Technical University Eindhoven](https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai)"
  
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - references.qmd

format:
  html:
    theme: cosmo